site_name: "MDTC: Documentation"
dev_addr: "127.0.0.1:8888"

theme:
  name: "material"
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - mkdocstrings
  - search
  - gen-files:
      scripts:
        - autodoc.py

nav:
  - README.md
  - docs/mdtc.md
  - docs/errors.md
  - docs/singleton.md