name: 'Test, Build and Deploy'
on: [push]


jobs:

  test-and-lint:
    name: Flake8, MyPy, Pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pip install poetry
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - name: Install dependencies
      run: |
        poetry install --with dev,test
    - name: flake8
      run: |
        poetry run flake8 mdtc
    - name: mypy
      run: |
        poetry run mypy -p mdtc
    - name: pytest
      run: |
        poetry run pytest -vvv tests

  # TODO: Future section for autodoc and push to PYPI..
  # build-and-deploy-to-pypi:
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/master'
  #   name: Build and deploy to PYPI
  #   runs-on: ubuntu-latest
  #   needs: test-and-lint

  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2